# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target '品茶2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 品茶2

  target '品茶2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '品茶2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SwiftyJSON'
pod 'Alamofire'

end
